name: Test KICS action PR comment

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Mkdir results-dir
        # make sure results dir is created
      run: mkdir -p results-dir
    - name: run kics Scan
      uses: msandeep12/kics-github-action@master
      with:
        path: 'aws/aws_domain_redirect'
        type: terraform
        platform_type: terraform
        #ignore_on_exit: results
        exclude_queries: fc5109bf-01fd-49fb-8bde-4492b543c34a
        fail_on_threshold: 'high>200,low<500'
        output_path:  results-dir/
    - name: display kics results
      run: |
        cat  results-dir/results.json