name: Test KICS action PR comment

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Mkdir results-dir
        # make sure results dir is created
      run: mkdir -p results-dir
    - name: run kics Scan
      uses: msandeep12/kics-github-action@master
      with:
        path: 'aws/aws_mailgun_domain'
        type: terraform
        platform_type: terraform
        ignore_on_exit: results
        fail_on: 'low'
        exclude_queries: fc5109bf-01fd-49fb-8bde-4492b543c34a,2a153952-2544-4687-bcc9-cc8fea814a9b #,e592a0c5-5bdb-414c-9066-5dba7cdea370
        fail_on_threshold: 'low>20,high>50,medium>20'
        output_path:  results-dir/
        exclude_severities: 'info'
    - name: display kics results
      run: |
        cat  results-dir/results.json